import { Navbar } from "@/components/navbar_component/navbar";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["vietnamese"],
  weight: "400",
  display: "swap",
});
// export const metadata = {
//   title: "Cộng đồng Flutter Việt Nam",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-100`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
